#!/usr/bin/env python3
"""Turns the compiled SPIR-V modules into a C++ header so the game has no
runtime dependency on shader files."""

import pathlib
import sys

HEADER = """// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Zilla contributors.
//
// Generated by tools/embed_shaders.py - do not edit by hand.
#ifndef ZILLA_GFX_EMBEDDED_SHADERS_H
#define ZILLA_GFX_EMBEDDED_SHADERS_H

#include <cstddef>
#include <cstdint>

namespace zilla {{

{content}
}} // namespace zilla

#endif // ZILLA_GFX_EMBEDDED_SHADERS_H
"""


def array_name(path: pathlib.Path) -> str:
    return path.stem.replace(".", "_").replace("-", "_")


def main(argv):
    if len(argv) < 2:
        print("usage: embed_shaders.py OUT.h IN.spv [IN.spv ...]")
        return 1

    out_path = pathlib.Path(argv[1])
    blocks = []
    for name in argv[2:]:
        path = pathlib.Path(name)
        data = path.read_bytes()
        if len(data) % 4 != 0:
            print(f"{name}: not a SPIR-V module (size is not a multiple of 4)")
            return 1
        words = [data[i:i + 4] for i in range(0, len(data), 4)]
        values = ", ".join("0x%08X" % int.from_bytes(w, "little") for w in words)
        blocks.append(
            "inline constexpr uint32_t %s[] = {\n\t%s,\n};\n"
            "inline constexpr size_t %s_size = sizeof(%s);"
            % (array_name(path), values, array_name(path), array_name(path))
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(HEADER.format(content="\n\n".join(blocks)) + "\n")
    print("wrote %s" % out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
