Skip to content
Zilla
Repository navigation
Code
Pull requests
Agents
🔗 GHA
Update android_builds.yml #37
Annotations
1 error and 1 warning
🤖 Android 
/
 Editor (SCU, arm64, ultra-fast)
failed now in 2m 2s
1s
17s
0s
2s
1s
18s
2s
1m 18s
0s
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Run actions/upload-artifact@v4
(node:3508) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Multiple search paths detected. Calculating the least common ancestor of all paths
The least common ancestor is /home/runner/work/Zilla/Zilla. This will be the root directory of the artifact
Error: No files were found with the provided path: platform/android/java/app/build/outputs/apk/**/*.apk
platform/android/java/build/outputs/apk/**/*.apk
platform/android/java/app/build/outputs/bundle/**/*.aab
platform/android/java/build/outputs/bundle/**/*.aab
platform/android/java/lib/build/outputs/aar/*.aar
bin/*.apk
bin/*.aab. No artifacts will be uploaded.
0s
0s
0s
0s
0s
0s
